version: "3"

services:
  bookshop-backend:
    container_name: bookshop-backend
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: dockerfile-dev
    ports:
      - "8081:8080"
      - "5005:5005"
    volumes:
      - ./src:/app/src

  database:
      image: mysql:5.7.16
      container_name: bookshop-db
      ports:
        - "3306:3306"
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
      environment:
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "user"
        MYSQL_DATABASE: "bookshop"
        MYSQL_ROOT_PASSWORD: "root"
      volumes:
        - ./db-data:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  testing-db:
      image: mysql:5.7.16
      container_name: bookshop-testing-db
      ports:
        - "3307:3306"
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
      environment:
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "user"
        MYSQL_DATABASE: "bookshop"
        MYSQL_ROOT_PASSWORD: "root"
      volumes:
        - ./testing-db-data:/var/lib/mysql
